trigger:
- none

pr:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: 'true'
  clean: 'true'

- script: |
    find . -mindepth 2 -name Dockerfile
  displayName: 'test'
