trigger:
- none

pr:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: 'true'
  clean: 'true'

- script: |
    git config --global user.email 'pipeline@azure.com'
    git config --global user.name 'Azure Pipeline'
  displayName: 'git config'

- script: |
    git checkout -b test
    git push --set-upstream origin test
  displayName: 'git undo detached state'

- script: |
    docker container ls
  displayName: 'test'
