trigger:
- none

pr:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: 'true'
  clean: 'true'

- script: |
    find . -mindepth 2 -name Dockerfile
    search="\(from.*$DOCKER_USER/$DOCKER_REPO\):.*"
    version=WOUTER
    replace="\1:$version"
    sed --help
    find . -mindepth 2 -name Dockerfile -exec sed -i "s|$search|$replace|ig" {} \;
    find . -mindepth 2 -name Dockerfile -exec cat {} \;
  displayName: 'test'
