trigger:
- none

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo '$(DOCKER_PASSWORD)'
  displayName: 'check variable'

- script: docker login -u=docker4gis -p='$(DOCKER_PASSWORD)' docker.io
  displayName: 'docker login'

- script: npx --yes docker4gis@latest build
  displayName: 'docker4gis build'
