trigger:
- none

pr:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: 'true'
  clean: 'true'

- script: |
    git config --global user.email 'pipeline@azure.com'
    git config --global user.name 'Azure Pipeline'
  displayName: 'git config'

- script: |
    git checkout -b main
    git push --set-upstream origin main
  displayName: 'git undo detached state'

- script: |
    find . -mindepth 2 -name Dockerfile
    search="\(from.*docker4gis/proxy\):.*"
    version=WOUTER
    replace="\1:$version"
    find . -mindepth 2 -name Dockerfile -exec sed -i "s|$search|$replace|ig" {} \;
    find . -mindepth 2 -name Dockerfile -exec cat {} \;
    git add .
    git status
  displayName: 'test'
